### ISSUE TITLE
Inference with GPU?

### ISSUE THREAD

**Issue by rmitsch** [lukemelas/EfficientNet-PyTorch#133]
When inferring classes with the pretrained (b7) model only my CPU is utilized, the GPU is pretty idle. pytorch seems able to work with my GPU though:
```
print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))
print(torch.cuda.is_available())
```
yields
```
0
<torch.cuda.device object at 0x7fc050154198>
1
GeForce RTX 2080
True
```

Any idea as to why my GPU is not used?

**Comment by rmitsch** [comment]
```
model = EfficientNet.from_pretrained(model_name)
model.cuda()
model.eval();
...
logits = model(img.cuda())
...
```
does the trick.
